"""Make floorstate.id an IDENTITY and reset counter

Revision ID: 0a9c9a048b97
Revises: 5a6bed25c1c6
Create Date: 2025-09-17 18:29:05.576836

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0a9c9a048b97'
down_revision: Union[str, Sequence[str], None] = '5a6bed25c1c6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute("""
    DO $$
    DECLARE
        id_status text;
        has_default boolean;
        max_id bigint;
    BEGIN
        -- is it already identity?
        SELECT is_identity INTO id_status
        FROM information_schema.columns
        WHERE table_schema = 'public'
            AND table_name = 'floorstate'
                AND column_name = 'id';

        IF id_status IS DISTINCT FROM 'YES' THEN
            -- old SERIAL default present?
            SELECT (column_default IS NOT NULL) INTO has_default
            FROM information_schema.columns
            WHERE table_schema = 'public'
                    AND table_name = 'floorstate'
                    AND column_name = 'id';

            IF has_default THEN
                EXECUTE 'ALTER TABLE public.floorstate ALTER COLUMN id DROP DEFAULT';
            END IF;

            EXECUTE 'ALTER TABLE public.floorstate ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY';
        END IF;

        -- restart to max(id)+1
        SELECT COALESCE(MAX(id), 0) + 1 INTO max_id FROM public.floorstate;
        EXECUTE format('ALTER TABLE public.floorstate ALTER COLUMN id RESTART WITH %s', max_id);
    END$$;
    """)


def downgrade() -> None:
    op.execute("""
    DO $$
    BEGIN
        -- remove identity if present (leaves plain int PK)
        EXECUTE 'ALTER TABLE public.floorstate ALTER COLUMN id DROP IDENTITY IF EXISTS';
    END$$;
    """)