"""fix intervention id identity

Revision ID: 113ab1d9a780
Revises: 478d251189b0
Create Date: 2025-09-25 17:27:45.595848

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '113ab1d9a780'
down_revision: Union[str, Sequence[str], None] = '478d251189b0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

TABLE = "intervention"
COL = "id"

def upgrade() -> None:
    conn = op.get_bind()

    # is column already identity?
    is_identity = conn.execute(sa.text("""
        SELECT c.is_identity = 'YES'
        FROM information_schema.columns c
        WHERE c.table_name = :t AND c.column_name = :c
    """), {"t": TABLE, "c": COL}).scalar()

    # compute next value (handles empty table)
    next_id = conn.execute(sa.text(f"SELECT COALESCE(MAX({COL}), 0) + 1 FROM {TABLE}")).scalar_one()

    if is_identity:
        # already identity: just restart counter
        conn.exec_driver_sql(f"ALTER TABLE {TABLE} ALTER COLUMN {COL} RESTART WITH {int(next_id)}")
        return

    # not identity yet. First, drop any default (e.g., leftover nextval)
    conn.execute(sa.text(f"ALTER TABLE {TABLE} ALTER COLUMN {COL} DROP DEFAULT"))

    # add identity (BY DEFAULT so you can still insert explicit ids if needed)
    conn.exec_driver_sql(f"""
        ALTER TABLE {TABLE}
        ALTER COLUMN {COL} ADD GENERATED BY DEFAULT AS IDENTITY
    """)

    # restart identity to max+1
    conn.exec_driver_sql(f"ALTER TABLE {TABLE} ALTER COLUMN {COL} RESTART WITH {int(next_id)}")

def downgrade() -> None:
    conn = op.get_bind()
    conn.exec_driver_sql(f"ALTER TABLE {TABLE} ALTER COLUMN {COL} DROP IDENTITY IF EXISTS")