"""make eventstage.id identity

Revision ID: 2eb9b8700761
Revises: b426683e86f0
Create Date: 2025-09-17 17:33:25.285019

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2eb9b8700761'
down_revision: Union[str, Sequence[str], None] = 'b426683e86f0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute("ALTER TABLE eventstage ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY")


def downgrade() -> None:
    """Downgrade schema."""
    pass
