"""fix rorinvite id identity

Revision ID: 411269d44e69
Revises: 89d87af9d6be
Create Date: 2025-09-26 17:29:35.754403

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '411269d44e69'
down_revision: Union[str, Sequence[str], None] = '89d87af9d6be'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

TABLE = "rorinvite"
COL = "id"

def upgrade() -> None:
    conn = op.get_bind()

    # Is it already an identity column?
    is_identity = conn.execute(sa.text("""
        SELECT c.is_identity = 'YES'
        FROM information_schema.columns c
        WHERE c.table_name = :t AND c.column_name = :c
    """), {"t": TABLE, "c": COL}).scalar()

    # Find the next value (works if table is empty too)
    next_id = conn.execute(sa.text(f"SELECT COALESCE(MAX({COL}), 0) + 1 FROM {TABLE}")).scalar_one()

    if not is_identity:
        # Drop any lingering default first (e.g., from SERIAL/sequence)
        conn.exec_driver_sql(f"ALTER TABLE {TABLE} ALTER COLUMN {COL} DROP DEFAULT")
        # Convert to identity (BY DEFAULT lets you still set ids manually if needed)
        conn.exec_driver_sql(f"""
            ALTER TABLE {TABLE}
            ALTER COLUMN {COL} ADD GENERATED BY DEFAULT AS IDENTITY
        """)

    # Ensure the identity sequence starts after current MAX(id)
    conn.exec_driver_sql(f"ALTER TABLE {TABLE} ALTER COLUMN {COL} RESTART WITH {int(next_id)}")


def downgrade() -> None:
    # Only drop identity; you can add back a default/sequence if you really need to.
    conn = op.get_bind()
    conn.exec_driver_sql(f"ALTER TABLE {TABLE} ALTER COLUMN {COL} DROP IDENTITY IF EXISTS")