"""fix notification id identity

Revision ID: 478d251189b0
Revises: 192e31cf8fa9
Create Date: 2025-09-22 20:44:34.501718

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '478d251189b0'
down_revision: Union[str, Sequence[str], None] = '192e31cf8fa9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def _ensure_identity(table: str, col: str = "id"):
    conn = op.get_bind()

    # if column already identity, nothing to do
    is_identity = conn.execute(sa.text("""
        SELECT c.is_identity = 'YES'
        FROM information_schema.columns c
        WHERE c.table_name = :t AND c.column_name = :c
    """), {"t": table, "c": col}).scalar()

    # compute next value
    next_id = conn.execute(sa.text(f"SELECT COALESCE(MAX({col}), 0) + 1 FROM {table}")).scalar_one()

    if is_identity:
        # just restart so next insert is correct
        conn.exec_driver_sql(f"ALTER TABLE {table} ALTER COLUMN {col} RESTART WITH {int(next_id)}")
        return

    # If there is an old default or sequence, drop it first
    # (safe even if none present)
    conn.execute(sa.text(f"ALTER TABLE {table} ALTER COLUMN {col} DROP DEFAULT"))

    # Add identity (BY DEFAULT lets you still insert explicit ids if needed)
    conn.exec_driver_sql(f"""
        ALTER TABLE {table}
        ALTER COLUMN {col} ADD GENERATED BY DEFAULT AS IDENTITY
    """)

    # Restart identity to max+1
    conn.exec_driver_sql(f"ALTER TABLE {table} ALTER COLUMN {col} RESTART WITH {int(next_id)}")


def upgrade() -> None:
    _ensure_identity("notification")


def downgrade() -> None:
    conn = op.get_bind()
    conn.exec_driver_sql("ALTER TABLE notification ALTER COLUMN id DROP IDENTITY IF EXISTS")