"""fix event.id identity and drop stages_json

Revision ID: 50b00e80fc58
Revises: 09dd17a13440
Create Date: 2025-09-17 16:54:35.670810

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '50b00e80fc58'
down_revision: Union[str, Sequence[str], None] = '09dd17a13440'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # If the column isn't already an identity, add it.
    op.execute("ALTER TABLE event ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY")

    # If you still have the old JSON column, drop it now
    with op.batch_alter_table("event") as batch:
        try:
            batch.drop_column("stages_json")
        except Exception:
            # column may already be gone; ignore
            pass


def downgrade() -> None:
    # Downgrade: remove identity (optional), and add stages_json back (optional)
    # Removing identity is a bit fiddly; you can skip if not needed.
    with op.batch_alter_table("event") as batch:
        batch.add_column(sa.Column("stages_json", sa.JSON(), nullable=True))