"""fix all identity

Revision ID: 5a6bed25c1c6
Revises: ac1f945e0548
Create Date: 2025-09-17 18:19:44.831582

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5a6bed25c1c6'
down_revision: Union[str, Sequence[str], None] = 'ac1f945e0548'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    conn = op.get_bind()

    # List of tables to fix
    tables = ["question", "agendaproposal", "event", "eventstage", "proposalroom"]

    # One DO block per table keeps error context clear
    for t in tables:
        op.execute(f"""
        DO $$
        DECLARE
            id_status text;
            has_default boolean;
            max_id bigint;
        BEGIN
            -- Is id already an identity column?
            SELECT is_identity
            INTO id_status
            FROM information_schema.columns
            WHERE table_schema = 'public'
              AND table_name = '{t}'
              AND column_name = 'id';

            IF id_status IS DISTINCT FROM 'YES' THEN
                -- If not identity, see if there is a default (e.g., old SERIAL nextval)
                SELECT (column_default IS NOT NULL)
                INTO has_default
                FROM information_schema.columns
                WHERE table_schema = 'public'
                  AND table_name = '{t}'
                  AND column_name = 'id';

                IF has_default THEN
                    -- It's not identity, so it's safe to drop the default before adding identity
                    EXECUTE 'ALTER TABLE public.{t} ALTER COLUMN id DROP DEFAULT';
                END IF;

                -- Now make it an identity column
                EXECUTE 'ALTER TABLE public.{t} ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY';
            END IF;

            -- Reset the identity counter to max(id)+1
            EXECUTE format('SELECT COALESCE(MAX(id), 0) + 1 FROM public.{t}');
            SELECT COALESCE(MAX(id), 0) + 1 INTO max_id FROM public.{t};

            -- RESTART works for identity columns
            EXECUTE format('ALTER TABLE public.{t} ALTER COLUMN id RESTART WITH %s', max_id);
        END$$;
        """)


def downgrade() -> None:
    # Make IDs plain integers again (no auto-generation)
    for t in ["question", "agendaproposal", "event", "eventstage", "proposalroom"]:
        op.execute(f"""
        DO $$
        BEGIN
            -- Drop identity if present; ignore if not
            EXECUTE 'ALTER TABLE public.{t} ALTER COLUMN id DROP IDENTITY IF EXISTS';
            -- Do not restore any old sequences; this leaves a plain integer PK
        END$$;
        """)
