"""fix identities + general_floor_link fk + intervention self fk

Revision ID: 739b057e79b4
Revises: 113ab1d9a780
Create Date: 2025-09-25 18:55:45.287666

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '739b057e79b4'
down_revision: Union[str, Sequence[str], None] = '113ab1d9a780'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def _q(ident: str) -> str: return '"' + ident.replace('"','""') + '"'

def _add_identity(table: str, col: str = "id", schema: str | None = None):
    sch = schema or 'public'
    qtbl = f'{_q(schema) + "." if schema else ""}{_q(table)}'
    qcol = _q(col)

    sql = f"""
DO $$
DECLARE
  col_is_identity boolean;
BEGIN
  SELECT (c.is_identity = 'YES')
    INTO col_is_identity
  FROM information_schema.columns c
  WHERE c.table_schema = '{sch}'
    AND c.table_name   = '{table}'
    AND c.column_name  = '{col}';

  IF col_is_identity IS DISTINCT FROM TRUE THEN
    BEGIN
      ALTER TABLE {qtbl}
        ALTER COLUMN {qcol} ADD GENERATED BY DEFAULT AS IDENTITY;
    EXCEPTION
      WHEN duplicate_object THEN
        NULL;
    END;
  END IF;
END$$;
"""
    op.get_bind().exec_driver_sql(sql)

def upgrade() -> None:
    _add_identity("intervention")
    _add_identity("notification")
    _add_identity("speakerrequest")
    _add_identity("floorstate")
    _add_identity("proposalmessage")
    _add_identity("proposalroom")
    _add_identity("proposaldraft")
    _add_identity("agendaproposal")
    _add_identity("event")
    _add_identity("eventstage") # -- if your table name is "event_stage" use that instead
    _add_identity("question")
    _add_identity("draft")
    _add_identity("objection")
    _add_identity("user")
    _add_identity("role")
    _add_identity("session")
    _add_identity("eventsequence")  # -- if table is "eventsequence"

    # Fix bad FK on general_floor_link.question_id -> it must point to question.id
    # Drop existing wrong constraint(s) if present
    try:
        op.drop_constraint("general_floor_link_question_id_fkey", "general_floor_link", type_="foreignkey")
    except Exception:
        pass # ignore if it didn't exist / different name

    # Also ensure the column actually references the right table
    # (no column type change needed if both are INTEGER)
    op.create_foreign_key(
        "fk_gfl_question",
        "general_floor_link",
        "question",
        ["question_id"],
        ["id"],
        ondelete="CASCADE",
    )

    # Helpful self-FK on intervention.relates_to_id (keeps replies valid)
    try:
        op.create_foreign_key(
            "fk_intervention_relates",
            "intervention",
            "intervention",
            ["relates_to_id"],
            ["id"],
            ondelete="SET NULL",
        )
    except Exception:
        pass # already exists

    # Add index to speed up reply lookups (idempotent)
    op.create_index(
        "idx_intervention_relates_to",
        "intervention",
        ["relates_to_id"],
        unique=False,
        if_not_exists=True, # Alembic >=1.11; if not available, wrap in try/except
    )

def downgrade() -> None:
    try:
        op.drop_index("idx_intervention_relates_to", table_name="intervention")
    except Exception:
        pass
    try:
        op.drop_constraint("fk_intervention_relates", "intervention", type_="foreignkey")
    except Exception:
        pass
    try:
        op.drop_constraint("fk_gfl_question", "general_floor_link", type_="foreignkey")
    except Exception:
        pass