"""initial (clean)

Revision ID: 772b1eadc51e
Revises: 
Create Date: 2025-08-29 03:56:38.021558

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '772b1eadc51e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('draft',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('version_int', sa.Integer(), nullable=False),
    sa.Column('clauses_json', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('draft', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_draft_question_id'), ['question_id'], unique=False)

    op.create_table('event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('starts_at', sa.DateTime(), nullable=False),
    sa.Column('ends_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('floorstate',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('is_open', sa.Boolean(), nullable=False),
    sa.Column('speaking_time_sec', sa.Integer(), nullable=False),
    sa.Column('current_speaker_request_id', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('floorstate', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_floorstate_current_speaker_request_id'), ['current_speaker_request_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_floorstate_question_id'), ['question_id'], unique=True)

    op.create_table('intervention',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('by_user', sa.Integer(), nullable=False),
    sa.Column('local_no', sa.Integer(), nullable=True),
    sa.Column('body', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('relates_to_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('intervention', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_intervention_by_user'), ['by_user'], unique=False)
        batch_op.create_index(batch_op.f('ix_intervention_local_no'), ['local_no'], unique=False)
        batch_op.create_index(batch_op.f('ix_intervention_question_id'), ['question_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_intervention_relates_to_id'), ['relates_to_id'], unique=False)

    op.create_table('notification',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=True),
    sa.Column('type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('message', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('payload_json', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('notification', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notification_user_id'), ['user_id'], unique=False)

    op.create_table('objection',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('draft_id', sa.Integer(), nullable=False),
    sa.Column('clause_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('by_user', sa.Integer(), nullable=False),
    sa.Column('reason_code', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('alt_text', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('maintained', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('objection', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_objection_draft_id'), ['draft_id'], unique=False)

    op.create_table('proposal',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('by_user', sa.Integer(), nullable=False),
    sa.Column('point_key', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('op', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('text', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('sponsors_json', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('proposal', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_proposal_by_user'), ['by_user'], unique=False)
        batch_op.create_index(batch_op.f('ix_proposal_question_id'), ['question_id'], unique=False)

    op.create_table('question',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('rapporteur_id', sa.Integer(), nullable=False),
    sa.Column('decision_points_json', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('role',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('role', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_role_name'), ['name'], unique=True)

    op.create_table('rorinvite',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('target_intervention_id', sa.Integer(), nullable=True),
    sa.Column('from_user_id', sa.Integer(), nullable=False),
    sa.Column('to_user_id', sa.Integer(), nullable=False),
    sa.Column('kind', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('session',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('issued_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('session', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_session_token'), ['token'], unique=True)
        batch_op.create_index(batch_op.f('ix_session_user_id'), ['user_id'], unique=False)

    op.create_table('speakerrequest',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('kind', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('target_intervention_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('speakerrequest', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_speakerrequest_question_id'), ['question_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_speakerrequest_target_intervention_id'), ['target_intervention_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_speakerrequest_user_id'), ['user_id'], unique=False)

    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('handle', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('password_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('verified', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_user_handle'), ['handle'], unique=True)

    op.create_table('agendaproposal',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('proposer_id', sa.Integer(), nullable=True),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=160), nullable=False),
    sa.Column('background', sa.Text(), nullable=False),
    sa.Column('source_url', sqlmodel.sql.sqltypes.AutoString(length=2048), nullable=True),
    sa.Column('status', sa.Enum('pending', 'accepted', 'rejected', 'submitted', name='proposalstatus'), nullable=False),
    sa.Column('decided_by_id', sa.Integer(), nullable=True),
    sa.Column('decided_at', sa.DateTime(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['decided_by_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['event_id'], ['event.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['proposer_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('agendaproposal', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_agendaproposal_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_agendaproposal_title'), ['title'], unique=False)

    op.create_table('eventsequence',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('next_l_no', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['event.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('eventsequence', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_eventsequence_event_id'), ['event_id'], unique=True)

    op.create_table('eventstage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('starts_at', sa.DateTime(), nullable=False),
    sa.Column('ends_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['event.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('userrolelink',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'role_id')
    )
    op.create_table('general_floor_link',
    sa.Column('proposal_id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['proposal_id'], ['agendaproposal.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['question_id'], ['question.id'], ),
    sa.PrimaryKeyConstraint('proposal_id')
    )
    with op.batch_alter_table('general_floor_link', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_general_floor_link_question_id'), ['question_id'], unique=True)

    op.create_table('proposalroom',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('proposal_id', sa.Integer(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=160), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('sponsor_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['event.id'], ),
    sa.ForeignKeyConstraint(['proposal_id'], ['agendaproposal.id'], ),
    sa.ForeignKeyConstraint(['sponsor_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('proposalroom', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_proposalroom_title'), ['title'], unique=False)

    op.create_table('proposaldraft',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('proposal_id', sa.Integer(), nullable=False),
    sa.Column('room_id', sa.Integer(), nullable=True),
    sa.Column('sponsor_id', sa.Integer(), nullable=False),
    sa.Column('recalling', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('noting', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('welcoming', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('expressing_regret', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('expressing_deep_concern', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('emphasizing', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('decides', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('requests', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('calls_upon', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('encourages', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('cosigners_json', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('is_submitted', sa.Boolean(), nullable=False),
    sa.Column('l_number', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['event.id'], ),
    sa.ForeignKeyConstraint(['proposal_id'], ['agendaproposal.id'], ),
    sa.ForeignKeyConstraint(['room_id'], ['proposalroom.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sponsor_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('proposalmessage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('room_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('local_no', sa.Integer(), nullable=True),
    sa.Column('body', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['proposalmessage.id'], ),
    sa.ForeignKeyConstraint(['room_id'], ['proposalroom.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('room_id', 'local_no', name='uq_proposalmessage_room_local')
    )
    with op.batch_alter_table('proposalmessage', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_proposalmessage_local_no'), ['local_no'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('proposalmessage', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_proposalmessage_local_no'))

    op.drop_table('proposalmessage')
    op.drop_table('proposaldraft')
    with op.batch_alter_table('proposalroom', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_proposalroom_title'))

    op.drop_table('proposalroom')
    with op.batch_alter_table('general_floor_link', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_general_floor_link_question_id'))

    op.drop_table('general_floor_link')
    op.drop_table('userrolelink')
    op.drop_table('eventstage')
    with op.batch_alter_table('eventsequence', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_eventsequence_event_id'))

    op.drop_table('eventsequence')
    with op.batch_alter_table('agendaproposal', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_agendaproposal_title'))
        batch_op.drop_index(batch_op.f('ix_agendaproposal_status'))

    op.drop_table('agendaproposal')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_handle'))
        batch_op.drop_index(batch_op.f('ix_user_email'))

    op.drop_table('user')
    with op.batch_alter_table('speakerrequest', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_speakerrequest_user_id'))
        batch_op.drop_index(batch_op.f('ix_speakerrequest_target_intervention_id'))
        batch_op.drop_index(batch_op.f('ix_speakerrequest_question_id'))

    op.drop_table('speakerrequest')
    with op.batch_alter_table('session', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_session_user_id'))
        batch_op.drop_index(batch_op.f('ix_session_token'))

    op.drop_table('session')
    op.drop_table('rorinvite')
    with op.batch_alter_table('role', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_role_name'))

    op.drop_table('role')
    op.drop_table('question')
    with op.batch_alter_table('proposal', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_proposal_question_id'))
        batch_op.drop_index(batch_op.f('ix_proposal_by_user'))

    op.drop_table('proposal')
    with op.batch_alter_table('objection', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_objection_draft_id'))

    op.drop_table('objection')
    with op.batch_alter_table('notification', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notification_user_id'))

    op.drop_table('notification')
    with op.batch_alter_table('intervention', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_intervention_relates_to_id'))
        batch_op.drop_index(batch_op.f('ix_intervention_question_id'))
        batch_op.drop_index(batch_op.f('ix_intervention_local_no'))
        batch_op.drop_index(batch_op.f('ix_intervention_by_user'))

    op.drop_table('intervention')
    with op.batch_alter_table('floorstate', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_floorstate_question_id'))
        batch_op.drop_index(batch_op.f('ix_floorstate_current_speaker_request_id'))

    op.drop_table('floorstate')
    op.drop_table('event')
    with op.batch_alter_table('draft', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_draft_question_id'))

    op.drop_table('draft')
    # ### end Alembic commands ###
