"""fix identity on floorstate & speakerrequest id

Revision ID: 8728bb495184
Revises: a8dad0140810
Create Date: 2025-09-17 18:54:13.872064

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8728bb495184'
down_revision: Union[str, Sequence[str], None] = 'a8dad0140810'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def _ensure_identity(table, col="id"):
    # If the column already has IDENTITY, do nothing.
    op.execute(f"""
    DO $$
    BEGIN
      -- check if column is already identity
      IF NOT EXISTS (
        SELECT 1
        FROM information_schema.columns c
        WHERE c.table_name = '{table}'
          AND c.column_name = '{col}'
          AND c.is_identity = 'YES'
      ) THEN
        -- drop any DEFAULT nextval() so we can add identity cleanly
        EXECUTE 'ALTER TABLE {table} ALTER COLUMN {col} DROP DEFAULT';
        -- add identity (BY DEFAULT lets manual inserts still work)
        EXECUTE 'ALTER TABLE {table} ALTER COLUMN {col} ADD GENERATED BY DEFAULT AS IDENTITY';
      END IF;
    END
    $$;
    """)

def upgrade() -> None:
    _ensure_identity("floorstate")
    _ensure_identity("speakerrequest")


def downgrade() -> None:
    # Best-effort: convert identity back to plain integer, no default
    op.execute("""
    DO $$
    BEGIN
      IF EXISTS (
        SELECT 1 FROM information_schema.columns
        WHERE table_name='floorstate' AND column_name='id' AND is_identity='YES'
      ) THEN
        EXECUTE 'ALTER TABLE floorstate ALTER COLUMN id DROP IDENTITY IF EXISTS';
      END IF;
      IF EXISTS (
        SELECT 1 FROM information_schema.columns
        WHERE table_name='speakerrequest' AND column_name='id' AND is_identity='YES'
      ) THEN
        EXECUTE 'ALTER TABLE speakerrequest ALTER COLUMN id DROP IDENTITY IF EXISTS';
      END IF;
    END
    $$;
    """)