"""add identity to question.id

Revision ID: ac1f945e0548
Revises: ad7b3cbd784b
Create Date: 2025-09-17 18:14:54.732398

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ac1f945e0548'
down_revision: Union[str, Sequence[str], None] = 'ad7b3cbd784b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute("ALTER TABLE question ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY")


def downgrade() -> None:
    op.execute("ALTER TABLE question ALTER COLUMN id DROP IDENTITY IF EXISTS")
