"""add identity to agendaproposal.id

Revision ID: ad7b3cbd784b
Revises: 2eb9b8700761
Create Date: 2025-09-17 18:04:38.667989

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ad7b3cbd784b'
down_revision: Union[str, Sequence[str], None] = '2eb9b8700761'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute("ALTER TABLE agendaproposal ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY")
    op.execute("ALTER TABLE proposalroom ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY")

def downgrade() -> None:
    op.execute("ALTER TABLE agendaproposal ALTER COLUMN id DROP IDENTITY IF EXISTS")
    op.execute("ALTER TABLE proposalroom ALTER COLUMN id DROP IDENTITY IF EXISTS")
